// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUhXaGjuL--0AqYMulKZ_0xHEIXTs1EcA',
    appId: '1:908774424466:android:fafed90094978aff594b4b',
    messagingSenderId: '908774424466',
    projectId: 'noctaapp-ed0e0',
    databaseURL: 'https://noctaapp-ed0e0.firebaseio.com',
    storageBucket: 'noctaapp-ed0e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsviDHQl_oUNRM06thfsFDAesDtHvc-Cg',
    appId: '1:908774424466:ios:388be4b04f832c79594b4b',
    messagingSenderId: '908774424466',
    projectId: 'noctaapp-ed0e0',
    databaseURL: 'https://noctaapp-ed0e0.firebaseio.com',
    storageBucket: 'noctaapp-ed0e0.appspot.com',
    androidClientId: '908774424466-vgo6plsh51mh3dm540b7q4o0qre021ga.apps.googleusercontent.com',
    iosClientId: '908774424466-5bun36mjcm1qu2hfj8efg7h63v7h2h39.apps.googleusercontent.com',
    iosBundleId: 'com.anasmisbah.presenceApp',
  );
}
